name: l1metml
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - pytables
  - uproot
  - tensorflow
  - pandas
  - h5py
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - setGPU
    - mplhep
    - git+https://github.com/google/qkeras#egg=qkeras
    - git+https://github.com/fastmachinelearning/hls4ml@master#egg=hls4ml[profiling]
